// features/drivers/constants/dispatchProgress.js

const DISPATCH_PROGRESS = {
  WAITING_DRIVER_ACCEPTANCE: 0,
  DRIVER_ACCEPTED: 20,
  EN_ROUTE_PICKUP: 40,
  PICKUP_COMPLETED: 60,
  DELIVERY_IN_PROGRESS: 80,
  DELIVERED: 100,

  FAILED: 100,
  CANCELLED: 100,
}

export default DISPATCH_PROGRESS
