// features/drivers/constants/dispatchProgress.js

const DISPATCH_PROGRESS = {
  WAITING_DRIVER_ACCEPTANCE: 0,
  DRIVER_ACCEPTED: 14,
  DRIVER_EN_ROUTE_TO_PICKUP: 28,
  ARRIVED_PICKUP: 42,
  PICKED_UP: 57, // ✅ Changed from PICKUP_COMPLETED
  IN_TRANSIT: 71,
  ARRIVED_DESTINATION: 85,
  DELIVERED: 100,
  FAILED: 100,
  CANCELLED: 100,
}

export default DISPATCH_PROGRESS
