const TRACKING_STATUS = {
  CREATED: 'CREATED',

  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',

  DRIVER_EN_ROUTE_TO_PICKUP: 'DRIVER_EN_ROUTE_TO_PICKUP',

  ARRIVED_PICKUP: 'ARRIVED_PICKUP',

  PICKED_UP: 'PICKED_UP',

  IN_TRANSIT: 'IN_TRANSIT',

  STOPPED: 'STOPPED',

  ROUTE_DEVIATION: 'ROUTE_DEVIATION',

  ARRIVED_DESTINATION: 'ARRIVED_DESTINATION',

  DELIVERED: 'DELIVERED',

  FAILED: 'FAILED',

  RETURNING: 'RETURNING',

  RETURNED: 'RETURNED',

  CANCELLED: 'CANCELLED',
}

export default TRACKING_STATUS
