export const TRACKING_STATUS = {
  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',

  DRIVER_EN_ROUTE_TO_PICKUP: 'DRIVER_EN_ROUTE_TO_PICKUP',

  ARRIVED_PICKUP: 'ARRIVED_PICKUP',

  PICKED_UP: 'PICKED_UP',

  IN_TRANSIT: 'IN_TRANSIT',

  ARRIVED_DESTINATION: 'ARRIVED_DESTINATION',

  DELIVERED: 'DELIVERED',
}

export default TRACKING_STATUS
